#!/usr/bin/env bash
# configures an Nginx server so that /redirect_me is redirecting to another page

sudo apt-get -y update
sudo apt-get -y install nginx
echo "Hello World!" | sudo -a tee /var/www/html/index.html
sudo service nginx stop
redirect="server_name _;\n\trewrite ^\/redirect_me https:\/\/www.google.com permanent;"
sudo sed -i "s/server_name _;/$redirect/" /etc/nginx/sites-enabled/default
sudo service nginx restart
