#!/usr/bin/env bash
# configures an Nginx server so that /redirect_me is redirecting to another page

sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
echo -e 'Holberton School WebServer 2' | sudo tee -a /var/www/html/index.html
sudo service nginx stop
redirect="server_name _;\n\trewrite ^\/redirect_me https:\/\/www.youtube.com/watch?v=QH2-TGUlwu4 permanent;"
sudo sed -i "s/server_name _;/$redirect/" /etc/nginx/sites-enabled/default
sudo service nginx start
