#!/usr/bin/env bash
# install load balancer
sudo apt-get -y install software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.6
sudo apt-get -y update
sudo apt-get -y install haproxy=2.6.\*
echo -e "\nlisten www" | sudo tee /etc/haproxy/haproxy.cfg
echo -e "\tbind :80"  | sudo tee /etc/haproxy/haproxy.cfg
echo -e "\tbalance roundrobin"  | sudo tee /etc/haproxy/haproxy.cfg
echo -e "\tserver 65475-web-01 34.204.61.9"  | sudo tee /etc/haproxy/haproxy.cfg
echo -e "\tserver 65475-web-02 54.237.98.194"  | sudo tee /etc/haproxy/haproxy.cfg
sudo service haproxy restart
