#!/usr/bin/env bash
# displays To infinity and beyond indefinitely
# In between each iteration of the loop, add a sleep 2
# I am invincible!!! when receiving a SIGTERM signal

while : ;
do
	echo "To infinity and beyond"
	sleep 2
	trap 'echo "I am invincible!!!"' SIGTERM
done
