#!/usr/bin/env bash
# Displays content of the file /etc/passwd
# only display:
# 	username
# 	userid
# 	Home directory path for the user
while read -r passwd;
do
  echo "$passwd" | cut -d ':' -f1,3,6
done < "/etc/passwd"
